//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WindowsTerminal.rc
//
#define IDI_APPICON 101
#define IDI_APPICON_HC_B 102
#define IDI_APPICON_HC_W 103

#define IDI_APPICON_DEV 111
#define IDI_APPICON_DEV_HC_B 112
#define IDI_APPICON_DEV_HC_W 113

#define IDI_APPICON_PRE 121
#define IDI_APPICON_PRE_HC_B 122
#define IDI_APPICON_PRE_HC_W 123

#define IDS_ERROR_DIALOG_TITLE 201
#define IDS_HELP_DIALOG_TITLE 202
#define IDS_ERROR_ARCHITECTURE_FORMAT 203
#define IDS_X86_ARCHITECTURE 204
#define IDS_AMD64_ARCHITECTURE 205
#define IDS_ARM64_ARCHITECTURE 206
#define IDS_ARM_ARCHITECTURE 207
#define IDS_UNKNOWN_ARCHITECTURE 208

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 209
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
